### ISSUE TITLE
attrdict missing from requirements.txt

### ISSUE THREAD

**Issue by kagibson** [udacity/nd013-c2-fusion-starter#8]
When installing requirements.txt using pip, I get the following error:

```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mjt2owsq/wxpython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mjt2owsq/wxpython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-mjt2owsq/wxpython/pip-egg-info
         cwd: /tmp/pip-install-mjt2owsq/wxpython/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mjt2owsq/wxpython/setup.py", line 27, in <module>
        from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
      File "/tmp/pip-install-mjt2owsq/wxpython/buildtools/config.py", line 30, in <module>
        from attrdict import AttrDict
    ModuleNotFoundError: No module named 'attrdict'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
This is solved by installing attrdict.

**Comment by Petros626** [comment]
@kagibson Hey mate, is this repo still supported? Did you completed this project as private task?
